const fs = require('fs');
const path = require('path');

const batchSize = 150;
const stubs = JSON.parse(fs.readFileSync('.temp/all_stubs.json', 'utf8'));
const allKeys = Object.keys(stubs);

const currentBatch = allKeys.slice(0, batchSize);

// I will now provide high-quality translations for these first 150 words.
// This is a partial map, I will continue in next turns.
const translations = {
    "abandon": { uk: "покинути", el: "εγκαταλείπω", de: "verlassen", nl: "verlaten", pl: "porzucić", crh: "tastamaq" },
    "abroad": { uk: "за кордоном", el: "στο εξωτερικό", de: "im Ausland", nl: "in het buitenland", pl: "za granicą", crh: "ecnebiy memlekette" },
    "absolution": { uk: "відпущення гріхів", el: "άφεση", de: "Absolution", nl: "vergeving", pl: "rozgrzeszenie", crh: "günadan azat etüv" },
    "absorb": { uk: "поглинати", el: "απορροφώ", de: "absorbieren", nl: "absorberen", pl: "wchłaniać", crh: "emmek" },
    "abstract": { uk: "абстрактний", el: "αφηρημένος", de: "abstrakt", nl: "abstract", pl: "abstrakcyjny", crh: "murekkep" },
    "absurd": { uk: "абсурдний", el: "παράλογος", de: "absurd", nl: "absurd", pl: "absurdalny", crh: "absurd" },
    "accidentally": { uk: "випадково", el: "τυχαία", de: "zufällig", nl: "per ongeluk", pl: "przypadkowo", crh: "tesadüfen" },
    "accompany": { uk: "супроводжувати", el: "συνοδεύω", de: "begleiten", nl: "begeleiden", pl: "towarzyszyć", crh: "refaqat etmek" },
    "accomplish": { uk: "виконувати", el: "κατορθώνω", de: "erreichen", nl: "volbrengen", pl: "osiągnąć", crh: "becermek" },
    "accomplishment": { uk: "досягнення", el: "επίτευγμα", de: "Leistung", nl: "prestatie", pl: "osiągnięcie", crh: "becerüv" },
    "according_to": { uk: "згідно з", el: "σύμφωνα με", de: "gemäß", nl: "volgens", pl: "według", crh: "köre" },
    "accordingly": { uk: "відповідно", el: "αναλόγως", de: "entsprechend", nl: "dienovereenkomstig", pl: "odpowiednio", crh: "oña köre" },
    "accountable": { uk: "підзвітний", el: "υπόλογος", de: "verantwortlich", nl: "verantwoordelijk", pl: "odpowiedzialny", crh: "mesuliyetli" },
    "accountant": { uk: "бухгалтер", el: "λογιστής", de: "Buchhalter", nl: "boekhouder", pl: "księgowy", crh: "esapçı" },
    "accurately": { uk: "точно", el: "με ακρίβεια", de: "genau", nl: "nauwkeurig", pl: "dokładnie", crh: "doğruca" },
    "accused": { uk: "обвинувачений", el: "κατηγορούμενος", de: "angeklagt", nl: "beschuldigde", pl: "oskarżony", crh: "qabaatlanğan" },
    "acknowledge": { uk: "визнавати", el: "αναγνωρίζω", de: "anerkennen", nl: "erkennen", pl: "uznać", crh: "tanımaq" },
    "acquire": { uk: "набувати", el: "αποκτώ", de: "erwerben", nl: "verwerven", pl: "nabyć", crh: "almaq" },
    "acre": { uk: "акр", el: "ακρ", de: "Acker", nl: "acre", pl: "akr", crh: "akr" },
    "activate": { uk: "активувати", el: "ενεργοποιώ", de: "aktivieren", nl: "activeren", pl: "aktywować", crh: "faalleştirmek" },
    "activation": { uk: "активація", el: "ενεργοποίηση", de: "Aktivierung", nl: "activering", pl: "aktywacja", crh: "faalleştirüv" },
    "activist": { uk: "активіст", el: "ακτιβιστής", de: "Aktivist", nl: "activist", pl: "aktywista", crh: "faal" },
    "acute": { uk: "гострий", el: "οξύς", de: "akut", nl: "acuut", pl: "ostry", crh: "keskin" },
    "adaptation": { uk: "адаптація", el: "προσαρμογή", de: "Anpassung", nl: "aanpassing", pl: "adaptacja", crh: "uyğunlaştıruv" },
    "addiction": { uk: "залежність", el: "εθισμός", de: "Sucht", nl: "verslaving", pl: "uzależnienie", crh: "bağımlılıq" },
    "additionally": { uk: "додатково", el: "επιπλέον", de: "zusätzlich", nl: "bovendien", pl: "dodatkowo", crh: "mından ğayrı" },
    "adequate": { uk: "адекватний", el: "επαρκής", de: "angemessen", nl: "voldoende", pl: "adekwatny", crh: "yeterli" },
    "adequately": { uk: "адекватно", el: "επαρκώς", de: "angemessen", nl: "voldoende", pl: "adekwatnie", crh: "yeterli sürette" },
    "adhere": { uk: "дотримуватися", el: "προσκολλώμαι", de: "anhalten", nl: "zich houden aan", pl: "przestrzegać", crh: "uymaq" },
    "adjacent": { uk: "суміжний", el: "παρακείμενος", de: "benachbart", nl: "aangrenzend", pl: "sąsiedni", crh: "yanındaki" },
    "adjust": { uk: "налаштовувати", el: "ρυθμίζω", de: "anpassen", nl: "aanpassen", pl: "dostosować", crh: "ayarlama" },
    "adjustment": { uk: "регулювання", el: "προσαρμογή", de: "Anpassung", nl: "aanpassing", pl: "regulacja", crh: "ayarlama" },
    "administer": { uk: "керувати", el: "διοικώ", de: "verwalten", nl: "beheren", pl: "zarządzać", crh: "idare etmek" },
    "administrative": { uk: "адміністративний", el: "διοικητικός", de: "administrativ", nl: "administratief", pl: "administracyjny", crh: "idariy" },
    "administrator": { uk: "адміністратор", el: "διαχειριστής", de: "Administrator", nl: "beheerder", pl: "administrator", crh: "idareci" },
    "admission": { uk: "вхід", el: "είσοδος", de: "Eintritt", nl: "toelating", pl: "wstęp", crh: "kiriş" },
    "adolescent": { uk: "підліток", el: "έφηβος", de: "Jugendlicher", nl: "adolescent", pl: "nastolateκ", crh: "genç" },
    "adoption": { uk: "усиновлення", el: "υιοθεσία", de: "Adoption", nl: "adoptie", pl: "adopcja", crh: "evlâtlıqqa aluv" },
    "adverse": { uk: "несприятливий", el: "δυσμενής", de: "nachteilig", nl: "nadelig", pl: "niekorzystny", crh: "yaman" },
    "advocate": { uk: "відстоювати", el: "υποστηρίζω", de: "befürworten", nl: "pleiten voor", pl: "popierać", crh: "qorçalamaq" },
    "aesthetic": { uk: "естетичний", el: "αισθητικός", "de": "ästhetisch", "nl": "esthetisch", "pl": "estetyczny", "crh": "estetik" },
    "affection": { uk: "прихильність", el: "στοργή", de: "Zuneigung", nl: "genegenheid", pl: "uczucie", crh: "sevgi" },
    "aftermath": { uk: "наслідки", el: "επακόλουθο", de: "Nachwirkungen", nl: "nasleep", pl: "następstwa", crh: "netice" },
    "aggression": { uk: "агресія", el: "επιθετικότητα", de: "Aggression", nl: "agressie", pl: "agresja", crh: "tecavuz" },
    "agricultural": { uk: "сільськогосподарський", el: "γεωργικός", de: "landwirtschaftlich", nl: "landbouwkundig", pl: "rolny", crh: "ziraiy" },
    "aide": { uk: "помічник", el: "βοηθός", de: "Helfer", nl: "hulp", pl: "asystent", crh: "yardımcı" },
    "albeit": { uk: "хоча", el: "αν και", de: "obgleich", nl: "alhoewel", pl: "jakkolwiek", crh: "ise de" },
    "alert": { uk: "тривога", el: "συναγερμός", de: "Alarm", nl: "alert", pl: "alarm", crh: "telüke" },
    "alien": { uk: "чужинець", el: "εξωγήινος", de: "Außerirdischer", nl: "buitenaards wezen", pl: "obcy", crh: "ecnebiy" },
    "align": { uk: "вирівнювати", el: "ευθυγραμμίζω", de: "ausrichten", nl: "uitlijnen", pl: "wyrównać", crh: "tüzeltmek" },
    "alignment": { uk: "вирівнювання", el: "ευθυγράμμιση", de: "Ausrichtung", nl: "uitlijning", pl: "wyrównanie", crh: "tüzetüv" },
    "alike": { uk: "схожий", el: "όμοιος", de: "gleich", nl: "gelijk", pl: "podobny", crh: "meñzeş" },
    "allegation": { uk: "звинувачення", el: "ισχυρισμός", de: "Behauptung", nl: "bewering", pl: "zarzut", crh: "iddia" },
    "allege": { uk: "стверджувати", el: "ισχυρίζομαι", de: "behaupten", nl: "beweren", pl: "twierdzić", crh: "iddia etmek" },
    "allegedly": { uk: "нібито", el: "δήθεν", de: "angeblich", nl: "naar verluidt", pl: "rzekomo", crh: "iddiağa köre" },
    "allegiance": { uk: "вірність", el: "πίστη", de: "Treue", nl: "trouw", pl: "lojalność", crh: "sadıqlıq" },
    "alliance": { uk: "альянс", el: "συμμαχία", de: "Allianz", nl: "alliantie", pl: "przymierze", crh: "ittifaq" },
    "allocate": { uk: "розподіляти", el: "κατανέμω", de: "zuweisen", nl: "toewijzen", pl: "przydzielać", crh: "ayırmaq" },
    "allocation": { uk: "розподіл", el: "κατανομή", de: "Zuweisung", nl: "toewijzing", pl: "przydział", crh: "tahsis" },
    "allowance": { uk: "допомога", el: "επίδομα", de: "Zulage", nl: "toelage", pl: "zasiłek", crh: "maaş" },
    "ally": { uk: "союзник", el: "σύμμαχος", de: "Verbündeter", nl: "bondgenoot", pl: "sojusznik", crh: "ittifaqdaş" },
    "aluminium": { uk: "алюміній", el: "αλουμίνιο", de: "Aluminium", nl: "aluminium", pl: "aluminium", crh: "alüminyum" },
    "amateur": { uk: "аматор", el: "ερασιτέχνης", de: "Amateur", nl: "amateur", pl: "amator", crh: "amator" },
    "ambassador": { uk: "посол", el: "πρεσβευτής", de: "Botschafter", nl: "ambassadeur", pl: "ambasador", crh: "elçi" },
    "amend": { uk: "вносити зміни", el: "τροποποιώ", de: "ändern", nl: "wijzigen", pl: "nowelizować", crh: "tüzetmek" },
    "amendment": { uk: "поправка", el: "τροπολογία", de: "Änderung", nl: "amendement", pl: "poprawka", crh: "tüzetüv" },
    "amid": { uk: "серед", el: "μέσα σε", de: "mitten in", nl: "te midden van", pl: "pośród", crh: "arasında" },
    "analogy": { uk: "аналогія", el: "αναλογία", de: "Analogie", nl: "analoog", pl: "analogia", crh: "meñzeş" },
    "anchor": { uk: "якір", el: "άγκυρα", de: "Anker", nl: "anker", pl: "kotwica", crh: "lenger" },
    "angel": { uk: "ангел", el: "άγγελος", de: "Engel", nl: "engel", pl: "anioł", crh: "melek" },
    "anonymous": { uk: "анонімний", el: "ανώνυμος", de: "anonym", nl: "anoniem", pl: "anonimowy", crh: "gizli" },
    "anticipate": { uk: "передбачати", el: "προσδοκώ", de: "vorhersehen", nl: "voorzien", pl: "przewidywać", crh: "beklemek" },
    "anticipation": { uk: "передчуття", el: "προσδοκία", de: "Erwartung", nl: "verwachting", pl: "przewidywanie", crh: "beklev" },
    "appealing": { uk: "привабливий", el: "ελκυστικός", de: "ansprechend", nl: "aantrekkelijk", pl: "atrakcyjny", crh: "çekici" },
    "appetite": { uk: "апетит", el: "όρεξη", de: "Appetit", nl: "eetlust", pl: "apetyt", crh: "iştah" },
    "applicable": { uk: "застосовний", el: "εφαρμόσιμος", de: "anwendbar", nl: "toepasbaar", pl: "mający zastosowanie", crh: "uyğun" },
    "appointment": { uk: "призначення", el: "ραντεβού", de: "Termin", nl: "afspraak", pl: "spotkanie", crh: "tayin" },
    "appreciation": { uk: "вдячність", el: "εκτίμηση", de: "Wertschätzung", nl: "waardering", pl: "uznanie", crh: "minnetdarlıq" },
    "arbitrary": { uk: "довільний", el: "αυθαίρετος", de: "willkürlich", nl: "willekeurig", pl: "arbitralny", crh: "keyfiy" },
    "architectural": { uk: "архітектурний", el: "αρχιτεκτονικός", de: "architektonisch", nl: "architectonisch", pl: "architektoniczny", crh: "mimariy" },
    "archive": { uk: "архів", el: "αρχείο", de: "Archiv", nl: "archief", pl: "archiwum", crh: "arhiv" },
    "area": { uk: "сфера / площа", el: "περιοχή", de: "Fläche", nl: "oppervlakte", pl: "obszar", crh: "meydan" },
    "arena": { uk: "арена", el: "αρένα", de: "Arena", nl: "arena", pl: "arena", crh: "arena" },
    "arguably": { uk: "ймовірно", el: "αναμφισβήτητα", de: "wohl", nl: "misschien wel", pl: "prawdopodobnie", crh: "iddiağa köre" },
    "array": { uk: "масив", el: "σειρά", de: "Anordnung", nl: "reeks", pl: "szereg", crh: "sıra" },
    "articulate": { uk: "виразний", el: "εύγλωττος", de: "artikuliert", nl: "duidelijk", pl: "wyraźny", crh: "açıq" },
    "ash": { uk: "попіл", el: "στάχτη", de: "Asche", nl: "as", pl: "popiół", crh: "kül" },
    "aside": { uk: "вбік", el: "στην άκρη", de: "beiseite", nl: "opzij", pl: "na bok", crh: "bir tarafqa" },
    "aspiration": { uk: "прагнення", el: "φιλοδοξία", de: "Bestreben", nl: "ambitie", pl: "aspiracja", crh: "can atuv" },
    "assassination": { uk: "вбивство", el: "δολοφονία", de: "Attentat", nl: "moordaanslag", pl: "zamach", crh: "öldürüv" },
    "assault": { uk: "напад", el: "επίθεση", de: "Angriff", nl: "aanval", pl: "napaść", crh: "ücüm" },
    "assembly": { uk: "збори", el: "συνέλευση", de: "Versammlung", nl: "vergadering", pl: "zgromadzenie", crh: "meclis" },
    "assertion": { uk: "твердження", el: "ισχυρισμός", de: "Behauptung", nl: "bewering", pl: "twierdzenie", crh: "iddia" },
    "assurance": { uk: "запевнення", el: "διαβεβαίωση", de: "Versicherung", nl: "verzekering", pl: "zapewnienie", crh: "teminat" },
    "asylum": { uk: "притулок", el: "άσυλο", de: "Asyl", nl: "asiel", pl: "azyl", crh: "sığınacaq" },
    "atrocity": { uk: "звірство", el: "θηριωδία", de: "Gräueltat", nl: "wreedheid", pl: "okrucieństwo", crh: "veşilik" },
    "attendance": { uk: "відвідуваність", el: "παρουσία", de: "Anwesenheit", nl: "aanwezigheid", pl: "obecność", crh: "iştirak" },
    "attorney": { uk: "адвокат", el: "δικηγόρος", de: "Anwalt", nl: "advocaat", pl: "pełnomocnik", crh: "advokat" },
    "audit": { uk: "аудит", el: "έλεγχος", de: "Prüfung", nl: "audit", pl: "audyt", crh: "teftiş" },
    "authentic": { uk: "автентичний", el: "αυθεντικός", de: "authentisch", nl: "authentiek", pl: "autentyczny", crh: "asıl" },
    "auto": { uk: "авто", el: "αυτοκίνητο", de: "Auto", nl: "auto", pl: "auto", crh: "avto" },
    "autonomy": { uk: "автономія", el: "αυτονομία", de: "Autonomie", nl: "autonomie", pl: "autonomia", crh: "muhtariyet" },
    "availability": { uk: "доступність", el: "διαθεσιμότητα", de: "Verfügbarkeit", nl: "beschikbaarheid", pl: "dostępność", crh: "müsuitlik" },
    "await": { uk: "чекати", el: "περιμένω", de: "erwarten", nl: "afwachten", pl: "oczekiwać", crh: "beklemek" },
    "backdrop": { uk: "фон", el: "παρασκήνιο", de: "Hintergrund", nl: "achtergrond", pl: "tło", crh: "arqa plan" },
    "backing": { uk: "підтримка", el: "υποστήριξη", de: "Unterstützung", nl: "steun", pl: "poparcie", crh: "destek" },
    "backup": { uk: "резервне копіювання", el: "εφεδρικό", de: "Sicherung", nl: "reservekopie", pl: "kopia zapasowa", crh: "yedek" },
    "bail": { uk: "застава", el: "εγγύηση", de: "Kaution", nl: "borgtocht", pl: "kaucja", crh: "kefalet" },
    "ballot": { uk: "виборчий бюлетень", el: "ψηφοδέλτιο", de: "Stimmzettel", nl: "stembiljet", pl: "karta do głosowania", crh: "saylav kâğıtı" },
    "banner": { uk: "банер", el: "πανό", de: "Banner", nl: "banner", pl: "sztandar", crh: "bayraq" },
    "bare": { uk: "голий", el: "γυμνός", de: "nackt", nl: "kaal", pl: "nagis", crh: "çıplaq" },
    "barrel": { uk: "бочка", el: "βαρέλι", de: "Fass", nl: "vat", pl: "beczka", crh: "fıçı" },
    "bass": { uk: "бас", el: "μπάσο", de: "Bass", nl: "bas", pl: "bas", crh: "bas" },
    "battlefield": { uk: "поле бою", el: "πεδίο μάχης", de: "Schlachtfeld", nl: "slagveld", pl: "pole bitwy", crh: "cenk meydanı" },
    "bay": { uk: "затока", el: "κόλπος", de: "Bucht", nl: "baai", pl: "zatoka", crh: "körfez" },
    "beam": { uk: "промінь", el: "ακτίνα", de: "Strahl", nl: "straal", pl: "promień", crh: "şua" },
    "beast": { uk: "звір", el: "θηρίο", de: "Bestie", nl: "beest", pl: "bestia", crh: "ayvan" },
    "behalf": { uk: "від імені", el: "εκ μέρους", de: "Auftrag", nl: "naam", pl: "imieniu", crh: "adından" },
    "beloved": { uk: "улюблений", el: "αγαπημένος", de: "geliebt", nl: "geliefd", pl: "ukochany", crh: "sevimli" },
    "bench": { uk: "лава", el: "πάγκος", de: "Bank", nl: "bank", pl: "ławka", crh: "oturğıç" },
    "benchmark": { uk: "орієнтир", el: "σημείο αναφοράς", de: "Maßstab", nl: "referentiepunt", pl: "punkt odniesienia", crh: "ölçü" },
    "beneath": { uk: "під", el: "κάτω από", de: "unter", nl: "onder", pl: "pod", crh: "tübünde" },
    "beneficiary": { uk: "бенефіціар", el: "δικαιούχος", de: "Begünstigter", nl: "begunstigde", pl: "beneficjent", crh: "faydalanıcı" },
    "bind": { uk: "зв'язувати", el: "δένω", de: "binden", nl: "binden", pl: "wiązać", crh: "bağlamaq" },
    "biography": { uk: "біографія", el: "βιογραφία", de: "Biografie", nl: "biografie", pl: "biografia", crh: "tercimieiyal" },
    "bishop": { uk: "єпископ", el: "επίσκοπος", de: "Bischof", nl: "bisschop", pl: "biskup", crh: "piskoρos" },
    "bizarre": { uk: "дивний", el: "αλλόκοτος", de: "skurril", nl: "bizar", pl: "dziwaczny", crh: "acaip" },
    "blade": { uk: "лезо", el: "λεπίδα", de: "Klinge", nl: "blad", pl: "ostrze", crh: "bıçaq" },
    "blast": { uk: "вибух", el: "έκρηξη", de: "Explosion", nl: "explosie", pl: "podmuch", crh: "patlav" },
    "blend": { uk: "суміш", el: "μείγμα", de: "Mischung", nl: "mengsel", pl: "mieszanka", crh: "qarışma" },
    "bless": { uk: "благословляти", el: "ευλογώ", de: "segnen", nl: "zegenen", pl: "błogosławić", crh: "dua etmek" },
    "blessing": { uk: "благословення", el: "ευλογία", de: "Segen", nl: "zegen", pl: "błogosławieństwo", crh: "hayır-dua" },
    "boast": { uk: "хвалитися", el: "καυχιέμαι", de: "prahlen", nl: "opscheppen", pl: "chwalić się", crh: "maqtanmaq" },
    "bonus": { uk: "бонус", el: "μπόνους", de: "Bonus", nl: "bonus", pl: "premia", crh: "bahşiş" },
    "boom": { uk: "бум", el: "έκρηξη", de: "Aufschwung", nl: "bloei", pl: "hossa", crh: "artuv" },
    "bounce": { uk: "підстрибувати", el: "αναπηδώ", de: "hüpfen", nl: "stuiteren", pl: "odbić się", crh: "sıçramaq" },
    "boundary": { uk: "кордон", el: "σύνορο", de: "Grenze", nl: "grens", pl: "granica", crh: "sınır" },
    "bow": { uk: "лук / уклін", el: "τόξο", de: "Bogen", nl: "boog", pl: "ukłon", crh: "yay" },
    "breakdown": { uk: "поломка", el: "κατάρρευση", de: "Zusammenbruch", nl: "pech", pl: "awaria", crh: "bozuluv" },
    "breed": { uk: "порода", el: "ράτσα", de: "Rasse", nl: "ras", pl: "rasa", crh: "soy" },
    "broadband": { uk: "широкосмуговий", el: "ευρυζωνικός", de: "Breitband", nl: "breedband", pl: "szerokopasmowy", crh: "keniş bant" },
    "brutal": { uk: "брутальний", el: "βάναυσος", de: "brutal", nl: "brutaal", pl: "brutalny", crh: "veşi" },
    "buck": { uk: "бакс", el: "δολάριο", de: "Bock", nl: "dollar", pl: "dolar", crh: "buck" },
    "buddy": { uk: "приятель", el: "φιλαράκος", de: "Kumpel", nl: "maatje", pl: "kumpel", crh: "dost" },
    "buffer": { uk: "буфер", el: "ρυθμιστής", de: "Puffer", nl: "buffer", pl: "bufor", crh: "buffer" },
    "bulk": { uk: "маса", el: "όγκος", de: "Masse", nl: "massa", pl: "hurt", crh: "mıqdar" },
    "bureaucracy": { uk: "бюрократія", el: "γραφειοκρατία", de: "Bürokratie", nl: "bureaucratie", pl: "biurokracja", crh: "bürokratiya" },
    "burial": { uk: "поховання", el: "ταφή", de: "Begräbnis", nl: "begrafenis", pl: "pogrzeb", crh: "definetüv" },
    "burst": { uk: "вибух", el: "έκρηξη", de: "Ausbruch", nl: "uitbarsting", pl: "wybuch", crh: "patlav" },
    "calculation": { uk: "розрахунок", el: "υπολογισμός", de: "Berechnung", nl: "berekening", pl: "obliczenie", crh: "esaplav" },
    "canvas": { uk: "полотно", el: "καμβάς", de: "Leinwand", nl: "canvas", pl: "płótno", crh: "bez" },
    "capability": { uk: "можливість", el: "ικανότητα", de: "Fähigkeit", nl: "capaciteit", pl: "zdolność", crh: "qabiliyet" },
    "capitalism": { uk: "капіталізм", el: "καπιταλισμός", de: "Kapitalismus", nl: "kapitalisme", pl: "kapitalizm", crh: "kapitalizm" },
    "capitalist": { uk: "капіталіст", el: "καπιταλιστής", de: "Kapitalist", nl: "kapitalist", pl: "kapitalista", crh: "kapitalist" },
    "carriage": { uk: "вагон / карета", el: "βαγόνι", de: "Wagen", nl: "rijτούig", pl: "wagon", crh: "vagon" },
    "carve": { uk: "вирізати", el: "σκαλίζω", de: "schnitzen", nl: "snijden", pl: "rzeźbić", crh: "oymaq" },
    "casino": { uk: "казино", el: "καζίνο", de: "Kasino", nl: "casino", pl: "kasyno", crh: "kazino" },
    "casualty": { uk: "жертва", el: "θύμα", de: "Opfer", nl: "slachtoffer", pl: "ofiara", crh: "qurban" },
    "catalogue": { uk: "каталог", el: "κατάλογος", de: "Katalog", nl: "catalogus", pl: "katalog", crh: "cedvel" },
    "cater": { uk: "обслуговувати", el: "εξυπηρετώ", de: "beliefern", nl: "verzorgen", pl: "zaopatrywać", crh: "hızmet etmek" },
    "cattle": { uk: "худоба", el: "βοοειδή", de: "Rindvieh", nl: "vee", pl: "bydło", crh: "ayvanlar" },
    "caution": { uk: "обережність", el: "προσοχή", de: "Vorsicht", nl: "voorzichtigheid", pl: "ostrożność", crh: "titizlik" },
    "cautious": { uk: "обережний", el: "προσεκτικός", de: "vorsichtig", nl: "voorzichtig", pl: "ostrożny", crh: "titiz" },
    "cemetery": { uk: "цвинтар", el: "νεκροταφείο", de: "Friedhof", nl: "begraafplaats", pl: "cmentarz", crh: "mezaristan" },
    "chamber": { uk: "камера", el: "θάλαμος", de: "Kammer", nl: "kamer", pl: "izba", crh: "hucüre" }
};

const langs = ['uk', 'el', 'de', 'nl', 'pl', 'crh'];
const dictionary = JSON.parse(fs.readFileSync('.temp/full_dictionary.json', 'utf8'));

// Apply translations
Object.entries(translations).forEach(([key, data]) => {
    if (!dictionary[key]) dictionary[key] = {};
    langs.forEach(lang => {
        dictionary[key][lang] = data[lang];
    });
    // English is usually the key itself
    dictionary[key]['en'] = key;
});

fs.writeFileSync('.temp/full_dictionary.json', JSON.stringify(dictionary, null, 2));
console.log('Batch of 100 quality translations applied to dictionary.');
