import fs from "fs";
import path from "path";

// Translation dictionaries for A1 (as a start)
const translations = {
	de: {
		brother: "Bruder",
		sister: "Schwester",
		mother: "Mutter",
		father: "Vater",
		apple: "Apfel",
		water: "Wasser",
		bread: "Brot",
		house: "Haus",
		car: "Auto",
		book: "Buch",
		school: "Schule",
		teacher: "Lehrer",
		student: "Student",
		city: "Stadt",
		country: "Land",
		friend: "Freund",
		family: "Familie",
		time: "Zeit",
		day: "Tag",
		night: "Nacht",
		morning: "Morgen",
		evening: "Abend",
		year: "Jahr",
		month: "Monat",
		week: "Woche",
		world: "Welt",
		life: "Leben",
		hand: "Hand",
		eye: "Auge",
		head: "Kopf",
		body: "Körper",
		food: "Essen",
		money: "Geld",
		door: "Tür",
		window: "Fenster",
		table: "Tisch",
		chair: "Stuhl",
		bed: "Bett",
		dog: "Hund",
		cat: "Katze",
		bird: "Vogel",
		tree: "Baum",
		flower: "Blume",
		sun: "Sonne",
		moon: "Mond",
		star: "Stern",
		sky: "Himmel",
		sea: "Meer",
		river: "Fluss",
		mountain: "Berg",
		good: "gut",
		bad: "schlecht",
		big: "groß",
		small: "klein",
		new: "neu",
		old: "alt",
		happy: "glücklich",
		sad: "traurig",
		hot: "heiß",
		cold: "kalt",
		beautiful: "schön",
		easy: "einfach",
		hard: "schwer",
		fast: "schnell",
		slow: "langsam",
		young: "jung",
		long: "lang",
		short: "kurz",
	},
	nl: {
		brother: "broer",
		sister: "zus",
		mother: "moeder",
		father: "vader",
		apple: "appel",
		water: "water",
		bread: "brood",
		house: "huis",
		car: "auto",
		book: "boek",
		school: "school",
		teacher: "leraar",
		student: "student",
		city: "stad",
		country: "land",
		friend: "vriend",
		family: "familie",
		time: "tijd",
		day: "dag",
		night: "nacht",
		morning: "ochtend",
		evening: "avond",
		year: "jaar",
		month: "maand",
		week: "week",
		world: "wereld",
		life: "leven",
		hand: "hand",
		eye: "oog",
		head: "hoofd",
		body: "lichaam",
		food: "voedsel",
		money: "geld",
		door: "deur",
		window: "raam",
		table: "tafel",
		chair: "stoel",
		bed: "bed",
		dog: "hond",
		cat: "kat",
		bird: "vogel",
		tree: "boom",
		flower: "bloem",
		sun: "zon",
		moon: "maan",
		star: "ster",
		sky: "hemel",
		sea: "zee",
		river: "rivier",
		mountain: "berg",
		good: "goed",
		bad: "slecht",
		big: "groot",
		small: "klein",
		new: "nieuw",
		old: "oud",
		happy: "gelukkig",
		sad: "verdrietig",
		hot: "heet",
		cold: "koud",
		beautiful: "mooi",
		easy: "makkelijk",
		hard: "moeilijk",
		fast: "snel",
		slow: "langzaam",
		young: "jong",
		long: "lang",
		short: "kort",
	},
	crh: {
		brother: "qardaş",
		sister: "qızqardaş",
		mother: "ana",
		father: "baba",
		apple: "alma",
		water: "su",
		bread: "ötmek",
		house: "ev",
		car: "araba",
		book: "kitap",
		school: "mektep",
		teacher: "oca",
		student: "talebe",
		city: "şeer",
		country: "memleket",
		friend: "dost",
		family: "aile",
		time: "vaqıt",
		day: "kün",
		night: "gece",
		morning: "sabah",
		evening: "aqşam",
		year: "yıl",
		month: "ay",
		week: "afta",
		world: "dünya",
		life: "ömür",
		hand: "el",
		eye: "köz",
		head: "baş",
		body: "vucut",
		food: "aş",
		money: "para",
		door: "qapı",
		window: "pencere",
		table: "masa",
		chair: "stul",
		bed: "yataq",
		dog: "köpek",
		cat: "pışıq",
		bird: "quş",
		tree: "terek",
		flower: "çiçek",
		sun: "küneş",
		moon: "ay",
		star: "yıldız",
		sky: "kök",
		sea: "deñiz",
		river: "özen",
		mountain: "dağ",
		good: "yahşı",
		bad: "fena",
		big: "balaban",
		small: "kiçkene",
		new: "yañı",
		old: "eskі",
		happy: "mesüt",
		sad: "kederli",
		hot: "sıcaq",
		cold: "suvuq",
		beautiful: "dülber",
		easy: "qolay",
		hard: "qıyın",
		fast: "tez",
		slow: "yavaş",
		young: "genç",
		long: "uzun",
		short: "qısqa",
	},
};

const languages = ["de", "nl", "crh"];
const levels = [
	"A1.json",
	"A2.json",
	"B1.json",
	"B2.json",
	"C1.json",
	"C2.json",
];

languages.forEach((lang) => {
	levels.forEach((level) => {
		const filePath = `src/lib/data/translations/${lang}/levels/${level}`;
		if (!fs.existsSync(filePath)) return;

		let data = JSON.parse(fs.readFileSync(filePath, "utf8"));
		let changed = false;

		for (const [key, value] of Object.entries(data)) {
			// If value is identical to key (modulo suffixes) or just empty/missing
			const baseKey = key.split("_")[0];
			if (
				value.toLowerCase() === baseKey.toLowerCase() ||
				value === "" ||
				value === key
			) {
				if (translations[lang] && translations[lang][baseKey]) {
					data[key] = translations[lang][baseKey];
					changed = true;
				}
			}
		}

		if (changed) {
			fs.writeFileSync(filePath, JSON.stringify(data, null, 4));
			console.log(`Partially translated ${filePath}`);
		}
	});
});
