export const missingWords = {
	admit_verb: {
		uk: "визнавати",
		en: "admit",
		de: "zugeben",
		nl: "toegeven",
		crh: "itiraf etmek",
		transcription: "ədˈmɪt",
	},
	argue_1: {
		uk: "сперечатися",
		en: "argue",
		de: "streiten",
		nl: "ruziën",
		crh: "tartışmaq",
		transcription: "ˈɑːɡjuː",
	},
	break: {
		uk: "ламати",
		en: "break",
		de: "brechen",
		nl: "breken",
		crh: "sındırmaq",
		transcription: "breɪk",
	},
	build: {
		uk: "будувати",
		en: "build",
		de: "bauen",
		nl: "bouwen",
		crh: "qurmaq",
		transcription: "bɪld",
	},
	clean: {
		uk: "чистити",
		en: "clean",
		de: "putzen",
		nl: "schoonmaken",
		crh: "temizlemek",
		transcription: "kliːn",
	},
	complete_1: {
		uk: "завершувати",
		en: "complete",
		de: "vervollständigen",
		nl: "voltooien",
		crh: "bitirmek",
		transcription: "kəmˈpliːt",
	},
	cross_1: {
		uk: "перетинати",
		en: "cross",
		de: "überqueren",
		nl: "oversteken",
		crh: "keçmek",
		transcription: "krɒs",
	},
	dance: {
		uk: "танцювати",
		en: "dance",
		de: "tanzen",
		nl: "dansen",
		crh: "oynamaq",
		transcription: "dɑːns",
	},
	fall: {
		uk: "падати",
		en: "fall",
		de: "fallen",
		nl: "vallen",
		crh: "tüşmek",
		transcription: "fɔːl",
	},
	fight: {
		uk: "битися",
		en: "fight",
		de: "kämpfen",
		nl: "vechten",
		crh: "küreşmek",
		transcription: "faɪt",
	},
	fix_repair: {
		uk: "ремонтувати",
		en: "fix",
		de: "reparieren",
		nl: "repareren",
		crh: "tamir etmek",
		transcription: "fɪks",
	},
	fly: {
		uk: "літати",
		en: "fly",
		de: "fliegen",
		nl: "vliegen",
		crh: "uçmaq",
		transcription: "flaɪ",
	},
	keep_1: {
		uk: "зберігати",
		en: "keep",
		de: "behalten",
		nl: "houden",
		crh: "saqlamaq",
		transcription: "kiːp",
	},
	lift: {
		uk: "піднімати",
		en: "lift",
		de: "heben",
		nl: "tillen",
		crh: "kötermek",
		transcription: "lɪft",
	},
	offer_2: {
		uk: "пропозиція",
		en: "offer",
		de: "Angebot",
		nl: "aanbod",
		crh: "teklif",
		transcription: "ˈɒfə",
	},
	report_2: {
		uk: "звіт",
		en: "report",
		de: "Bericht",
		nl: "rapport",
		crh: "esabat",
		transcription: "rɪˈpɔːt",
	},
	search_verb: {
		uk: "шукати",
		en: "search",
		de: "suchen",
		nl: "zoeken",
		crh: "qıdırmaq",
		transcription: "sɜːtʃ",
	},
	serve_2: {
		uk: "подавати",
		en: "serve",
		de: "servieren",
		nl: "serveren",
		crh: "hızmet etmek",
		transcription: "sɜːv",
	},
	sign_2: {
		uk: "підписувати",
		en: "sign",
		de: "unterschreiben",
		nl: "ondertekenen",
		crh: "imzalamaq",
		transcription: "saɪn",
	},
	touch_verb: {
		uk: "торкатися",
		en: "touch",
		de: "berühren",
		nl: "aanraken",
		crh: "tiymek",
		transcription: "tʌtʃ",
	},
	warn_verb: {
		uk: "попереджати",
		en: "warn",
		de: "warnen",
		nl: "waarschuwen",
		crh: "tenbilemek",
		transcription: "wɔːn",
	},
	cool_1: {
		uk: "прохолодний",
		en: "cool",
		de: "kühl",
		nl: "koel",
		crh: "salqın",
		transcription: "kuːl",
	},
	correct: {
		uk: "правильний",
		en: "correct",
		de: "richtig",
		nl: "correct",
		crh: "doğru",
		transcription: "kəˈrɛkt",
	},
	light: {
		uk: "світло",
		en: "light",
		de: "Licht",
		nl: "licht",
		crh: "yarıq",
		transcription: "laɪt",
	},
	open_adj: {
		uk: "відкритий",
		en: "open",
		de: "offen",
		nl: "open",
		crh: "açıq",
		transcription: "ˈəʊpən",
	},
	brother_1: {
		uk: "брат",
		en: "brother",
		de: "Bruder",
		nl: "broer",
		crh: "ağa",
		transcription: "ˈbrʌðə",
	},
	eye: {
		uk: "око",
		en: "eye",
		de: "Auge",
		nl: "oog",
		crh: "köz",
		transcription: "aɪ",
	},
	medicine_2: {
		uk: "медицина",
		en: "medicine",
		de: "Medizin",
		nl: "geneeskunde",
		crh: "tıbbiyet",
		transcription: "ˈmɛdsɪn",
	},
	bed: {
		uk: "ліжко",
		en: "bed",
		de: "Bett",
		nl: "bed",
		crh: "yataq",
		transcription: "bɛd",
	},
	bedroom: {
		uk: "спальня",
		en: "bedroom",
		de: "Schlafzimmer",
		nl: "slaapkamer",
		crh: "yataq odası",
		transcription: "ˈbɛdruːm",
	},
	chair: {
		uk: "стілець",
		en: "chair",
		de: "Stuhl",
		nl: "stoel",
		crh: "stul",
		transcription: "tʃeə",
	},
	floor_1: {
		uk: "поверх",
		en: "floor",
		de: "Stockwerk",
		nl: "verdieping",
		crh: "qat",
		transcription: "flɔː",
	},
	garden_1: {
		uk: "город",
		en: "garden",
		de: "Garten",
		nl: "tuin",
		crh: "bostan",
		transcription: "ˈɡɑːdn",
	},
	kitchen_1: {
		uk: "кухня",
		en: "kitchen",
		de: "Küche",
		nl: "keuken",
		crh: "aşhane",
		transcription: "ˈkɪtʃɪn",
	},
	living_room: {
		uk: "вітальня",
		en: "living room",
		de: "Wohnzimmer",
		nl: "woonkamer",
		crh: "musafirhan",
		transcription: "ˈlɪvɪŋ ruːm",
	},
	towel_1: {
		uk: "рушник",
		en: "towel",
		de: "Handtuch",
		nl: "handdoek",
		crh: "peşkir",
		transcription: "ˈtaʊəl",
	},
	drink_noun: {
		uk: "напій",
		en: "drink",
		de: "Getränk",
		nl: "drankje",
		crh: "içecek",
		transcription: "drɪŋk",
	},
	egg: {
		uk: "яйце",
		en: "egg",
		de: "Ei",
		nl: "ei",
		crh: "yumurta",
		transcription: "ɛɡ",
	},
	glass: {
		uk: "скло",
		en: "glass",
		de: "Glas",
		nl: "glas",
		crh: "şışa",
		transcription: "ɡlɑːs",
	},
	orange: {
		uk: "апельсин",
		en: "orange",
		de: "Orange",
		nl: "sinaasappel",
		crh: "apelsin",
		transcription: "ˈɒrɪndʒ",
	},
	engine_1: {
		uk: "двигун",
		en: "engine",
		de: "Motor",
		nl: "motor",
		crh: "motor",
		transcription: "ˈɛndʒɪn",
	},
	machine_1: {
		uk: "верстат",
		en: "machine",
		de: "Maschine",
		nl: "machine",
		crh: "tezgah",
		transcription: "məˈʃiːn",
	},
	station_1: {
		uk: "вокзал",
		en: "station",
		de: "Bahnhof",
		nl: "station",
		crh: "vokzal",
		transcription: "ˈsteɪʃ(ə)n",
	},
	way_1: {
		uk: "шлях (спосіб)",
		en: "way",
		de: "Weg",
		nl: "manier",
		crh: "yol",
		transcription: "weɪ",
	},
	earth_1: {
		uk: "земля (планета)",
		en: "earth",
		de: "Erde",
		nl: "aarde",
		crh: "yer",
		transcription: "ɜːθ",
	},
	space: {
		uk: "космос",
		en: "space",
		de: "Weltraum",
		nl: "ruimte",
		crh: "kosmos",
		transcription: "speɪs",
	},
	also_1: {
		uk: "також",
		en: "also",
		de: "auch",
		nl: "ook",
		crh: "da/de",
		transcription: "ˈɔːlsəʊ",
	},
	down: {
		uk: "вниз",
		en: "down",
		de: "runter",
		nl: "omlaag",
		crh: "aşağı",
		transcription: "daʊn",
	},
	so_1: {
		uk: "так",
		en: "so",
		de: "so",
		nl: "zo",
		crh: "öyle",
		transcription: "səʊ",
	},
	then_1: {
		uk: "потім",
		en: "then",
		de: "dann",
		nl: "dan",
		crh: "sonra",
		transcription: "ðɛn",
	},
	too_1: {
		uk: "занадто",
		en: "too",
		de: "zu",
		nl: "te",
		crh: "çoq",
		transcription: "tuː",
	},
	up: {
		uk: "вгору",
		en: "up",
		de: "hoch",
		nl: "omhoog",
		crh: "yuqarı",
		transcription: "ʌp",
	},
	bell: {
		uk: "дзвін",
		en: "bell",
		de: "Glocke",
		nl: "bel",
		crh: "çañ",
		transcription: "bɛl",
	},
	career: {
		uk: "кар'єра",
		en: "career",
		de: "Karriere",
		nl: "carrière",
		crh: "karyera",
		transcription: "kəˈrɪə",
	},
	class: {
		uk: "клас",
		en: "class",
		de: "Klasse",
		nl: "klas",
		crh: "sınıf",
		transcription: "klɑːs",
	},
	college: {
		uk: "коледж",
		en: "college",
		de: "College",
		nl: "college",
		crh: "kollej",
		transcription: "ˈkɒlɪdʒ",
	},
	course: {
		uk: "курс",
		en: "course",
		de: "Kurs",
		nl: "cursus",
		crh: "kurs",
		transcription: "kɔːs",
	},
	keyboard: {
		uk: "клавіатура",
		en: "keyboard",
		de: "Tastatur",
		nl: "toetsenbord",
		crh: "klaviatura",
		transcription: "ˈkiːbɔːd",
	},
	laptop: {
		uk: "ноутбук",
		en: "laptop",
		de: "Laptop",
		nl: "laptop",
		crh: "noutbuk",
		transcription: "ˈlæptɒp",
	},
	mark_1: {
		uk: "оцінка",
		en: "mark",
		de: "Note",
		nl: "cijfer",
		crh: "bağa",
		transcription: "mɑːk",
	},
	page: {
		uk: "сторінка",
		en: "page",
		de: "Seite",
		nl: "pagina",
		crh: "saife",
		transcription: "peɪdʒ",
	},
	paint_1: {
		uk: "фарба",
		en: "paint",
		de: "Farbe",
		nl: "verf",
		crh: "boya",
		transcription: "peɪnt",
	},
	part: {
		uk: "частина",
		en: "part",
		de: "Teil",
		nl: "deel",
		crh: "qısım",
		transcription: "pɑːt",
	},
	profession: {
		uk: "професія",
		en: "profession",
		de: "Beruf",
		nl: "beroep",
		crh: "zenaat",
		transcription: "prəˈfɛʃ(ə)n",
	},
	result: {
		uk: "результат",
		en: "result",
		de: "Ergebnis",
		nl: "resultaat",
		crh: "netice",
		transcription: "rɪˈzʌlt",
	},
	salary: {
		uk: "зарплата",
		en: "salary",
		de: "Gehalt",
		nl: "salaris",
		crh: "maaş",
		transcription: "ˈsæləri",
	},
	skill: {
		uk: "навичка",
		en: "skill",
		de: "Fähigkeit",
		nl: "vaardigheid",
		crh: "ustalıq",
		transcription: "skɪl",
	},
	subject_1: {
		uk: "тема",
		en: "subject",
		de: "Thema",
		nl: "onderwerp",
		crh: "mevzu",
		transcription: "ˈsʌbdʒɪkt",
	},
	website: {
		uk: "вебсайт",
		en: "website",
		de: "Webseite",
		nl: "website",
		crh: "sayt",
		transcription: "ˈwɛbsaɪt",
	},
	advice: {
		uk: "порада",
		en: "advice",
		de: "Rat",
		nl: "advies",
		crh: "mesleat",
		transcription: "ədˈvaɪs",
	},
	choice: {
		uk: "вибір",
		en: "choice",
		de: "Wahl",
		nl: "keuze",
		crh: "saylav",
		transcription: "tʃɔɪs",
	},
	error: {
		uk: "помилка",
		en: "error",
		de: "Fehler",
		nl: "fout",
		crh: "hata",
		transcription: "ˈɛrə",
	},
	event_occurrence: {
		uk: "подія",
		en: "event",
		de: "Ereignis",
		nl: "evenement",
		crh: "vaqia",
		transcription: "ɪˈvɛnt",
	},
	goal: {
		uk: "ціль",
		en: "goal",
		de: "Ziel",
		nl: "doel",
		crh: "maqsat",
		transcription: "ɡəʊl",
	},
	order_1: {
		uk: "порядок",
		en: "order",
		de: "Ordnung",
		nl: "volgorde",
		crh: "tertip",
		transcription: "ˈɔːdə",
	},
	past: {
		uk: "минуле",
		en: "past",
		de: "Vergangenheit",
		nl: "verleden",
		crh: "keçmiş",
		transcription: "pɑːst",
	},
	peace: {
		uk: "мир",
		en: "peace",
		de: "Frieden",
		nl: "vrede",
		crh: "barışıq",
		transcription: "piːs",
	},
	power_1: {
		uk: "сила",
		en: "power",
		de: "Kraft",
		nl: "kracht",
		crh: "küç",
		transcription: "ˈpaʊə",
	},
	service_1: {
		uk: "сервіс",
		en: "service",
		de: "Service",
		nl: "dienst",
		crh: "hızmet",
		transcription: "ˈsɜːvɪs",
	},
	sort_1: {
		uk: "вид",
		en: "sort",
		de: "Sorte",
		nl: "soort",
		crh: "tür",
		transcription: "sɔːt",
	},
	style: {
		uk: "стиль",
		en: "style",
		de: "Stil",
		nl: "stijl",
		crh: "usul",
		transcription: "staɪl",
	},
	success: {
		uk: "успіх",
		en: "success",
		de: "Erfolg",
		nl: "succes",
		crh: "muvafaqiyet",
		transcription: "səkˈsɛs",
	},
	system: {
		uk: "система",
		en: "system",
		de: "System",
		nl: "systeem",
		crh: "sistem",
		transcription: "ˈsɪstəm",
	},
	task: {
		uk: "завдання",
		en: "task",
		de: "Aufgabe",
		nl: "taak",
		crh: "vazife",
		transcription: "tɑːsk",
	},
	thought: {
		uk: "думка",
		en: "thought",
		de: "Gedanke",
		nl: "gedachte",
		crh: "fikir",
		transcription: "θɔːt",
	},
	trouble: {
		uk: "біда",
		en: "trouble",
		de: "Ärger",
		nl: "moeite",
		crh: "belâ",
		transcription: "ˈtrʌb(ə)l",
	},
	truth: {
		uk: "правда",
		en: "truth",
		de: "Wahrheit",
		nl: "waarheid",
		crh: "aqiqat",
		transcription: "truːθ",
	},
	type: {
		uk: "тип",
		en: "type",
		de: "Typ",
		nl: "type",
		crh: "tip",
		transcription: "taɪp",
	},
	view_1: {
		uk: "вид",
		en: "view",
		de: "Aussicht",
		nl: "uitzicht",
		crh: "körünüş",
		transcription: "vjuː",
	},
	war: {
		uk: "війна",
		en: "war",
		de: "Krieg",
		nl: "oorlog",
		crh: "cenk",
		transcription: "wɔː",
	},
	wish: {
		uk: "бажання",
		en: "wish",
		de: "Wunsch",
		nl: "wens",
		crh: "istek",
		transcription: "wɪʃ",
	},
	circle: {
		uk: "коло",
		en: "circle",
		de: "Kreis",
		nl: "cirkel",
		crh: "daire",
		transcription: "ˈsɜːk(ə)l",
	},
	gas_2: {
		uk: "газ (паливо)",
		en: "gas",
		de: "Benzin",
		nl: "benzine",
		crh: "benzin",
		transcription: "ɡæs",
	},
	grey: {
		uk: "сірий",
		en: "grey",
		de: "grau",
		nl: "grijs",
		crh: "sırımlı",
		transcription: "ɡreɪ",
	},
	purple: {
		uk: "фіолетовий",
		en: "purple",
		de: "lila",
		nl: "paars",
		crh: "eflatun",
		transcription: "ˈpɜːp(ə)l",
	},
	// ... adding more as needed
};
