export const missingWords2 = {
	bite: {
		uk: "кусати",
		en: "bite",
		de: "beißen",
		nl: "bijten",
		crh: "tişlemek",
		transcription: "baɪt",
	},
	blow: {
		uk: "дути",
		en: "blow",
		de: "blasen",
		nl: "blazen",
		crh: "üfürmek",
		transcription: "bləʊ",
	},
	create: {
		uk: "створювати",
		en: "create",
		de: "schaffen",
		nl: "creëren",
		crh: "yaratmaq",
		transcription: "kriːˈeɪt",
	},
	deal_verb: {
		uk: "мати справу",
		en: "deal",
		de: "handeln",
		nl: "handelen",
		crh: "iş yapmaq",
		transcription: "diːl",
	},
	deliver: {
		uk: "доставляти",
		en: "deliver",
		de: "liefern",
		nl: "leveren",
		crh: "teslim etmek",
		transcription: "dɪˈlɪvə",
	},
	depend: {
		uk: "залежати",
		en: "depend",
		de: "abhängen",
		nl: "afhangen",
		crh: "bağlı olmaq",
		transcription: "dɪˈpɛnd",
	},
	disappear: {
		uk: "зникати",
		en: "disappear",
		de: "verschwinden",
		nl: "verdwijnen",
		crh: "yoq olmaq",
		transcription: "ˌdɪsəˈpɪə",
	},
	exist: {
		uk: "існувати",
		en: "exist",
		de: "existieren",
		nl: "bestaan",
		crh: "bar olmaq",
		transcription: "ɪɡˈzɪst",
	},
	experience_2: {
		uk: "досвід",
		en: "experience",
		de: "Erfahrung",
		nl: "ervaring",
		crh: "tecrübe",
		transcription: "ɪkˈspɪərɪəns",
	},
	explore_verb: {
		uk: "досліджувати",
		en: "explore",
		de: "erforschen",
		nl: "verkennen",
		crh: "tetqiq etmek",
		transcription: "ɪkˈsplɔː",
	},
	express: {
		uk: "виражати",
		en: "express",
		de: "ausdrücken",
		nl: "uitdrukken",
		crh: "ifade etmek",
		transcription: "ɪkˈsprɛs",
	},
	float_verb: {
		uk: "плавати (на поверхні)",
		en: "float",
		de: "schweben",
		nl: "drijven",
		crh: "yüzmek",
		transcription: "fləʊt",
	},
	form: {
		uk: "форма",
		en: "form",
		de: "Form",
		nl: "vorm",
		crh: "şekil",
		transcription: "fɔːm",
	},
	hang_verb: {
		uk: "висіти",
		en: "hang",
		de: "hängen",
		nl: "hangen",
		crh: "asılmaq",
		transcription: "hæŋ",
	},
	inform: {
		uk: "інформувати",
		en: "inform",
		de: "informieren",
		nl: "informeren",
		crh: "haber bermek",
		transcription: "ɪnˈfɔːm",
	},
	knock_verb: {
		uk: "стукати",
		en: "knock",
		de: "klopfen",
		nl: "kloppen",
		crh: "qaqmaq",
		transcription: "nɒk",
	},
	lead: {
		uk: "вести",
		en: "lead",
		de: "führen",
		nl: "leiden",
		crh: "alıp barmaq",
		transcription: "liːd",
	},
	mix_2: {
		uk: "суміш",
		en: "mix",
		de: "Mischung",
		nl: "mix",
		crh: "qarışma",
		transcription: "mɪks",
	},
	notice: {
		uk: "помічати",
		en: "notice",
		de: "bemerken",
		nl: "opmerken",
		crh: "baıqamaq",
		transcription: "ˈnəʊtɪs",
	},
	pass: {
		uk: "проходити",
		en: "pass",
		de: "bestehen",
		nl: "slagen",
		crh: "keçmek",
		transcription: "pɑːs",
	},
	print: {
		uk: "друкувати",
		en: "print",
		de: "drucken",
		nl: "printen",
		crh: "bıraqmaq",
		transcription: "prɪnt",
	},
	produce: {
		uk: "виробляти",
		en: "produce",
		de: "produzieren",
		nl: "produceren",
		crh: "istisal etmek",
		transcription: "prəˈdjuːs",
	},
	provide: {
		uk: "забезпечувати",
		en: "provide",
		de: "anbieten",
		nl: "bieden",
		crh: "temin etmek",
		transcription: "prəˈvaɪd",
	},
	raise: {
		uk: "піднімати",
		en: "raise",
		de: "heben",
		nl: "verhogen",
		crh: "kötürmek",
		transcription: "reɪz",
	},
	realize: {
		uk: "усвідомлювати",
		en: "realize",
		de: "realisieren",
		nl: "beseffen",
		crh: "añlamaq",
		transcription: "ˈrɪəlaɪz",
	},
	record_verb: {
		uk: "записувати",
		en: "record",
		de: "aufnehmen",
		nl: "opnemen",
		crh: "yazmaq",
		transcription: "rɪˈkɔːd",
	},
	recycle: {
		uk: "переробляти",
		en: "recycle",
		de: "recyceln",
		nl: "recyclen",
		crh: "qayta işlemek",
		transcription: "ˌriːˈsaɪk(ə)l",
	},
	regret: {
		uk: "жалкувати",
		en: "regret",
		de: "bereuen",
		nl: "spijt hebben",
		crh: "pişman olmaq",
		transcription: "rɪˈɡrɛt",
	},
	rescue: {
		uk: "рятувати",
		en: "rescue",
		de: "retten",
		nl: "redden",
		crh: "qurtarmaq",
		transcription: "ˈrɛskjuː",
	},
	respect_verb: {
		uk: "поважати",
		en: "respect",
		de: "respektieren",
		nl: "respecteren",
		crh: "ürmet etmek",
		transcription: "rɪˈspɛkt",
	},
	scream_verb: {
		uk: "кричати",
		en: "scream",
		de: "schreien",
		nl: "schreeuwen",
		crh: "qıçırmaq",
		transcription: "skriːm",
	},
	stick_glue: {
		uk: "клеїти",
		en: "stick",
		de: "kleben",
		nl: "plakken",
		crh: "yapıştırmaq",
		transcription: "stɪk",
	},
	survive: {
		uk: "виживати",
		en: "survive",
		de: "überleben",
		nl: "overleven",
		crh: "sağ qalmaq",
		transcription: "səˈvaɪv",
	},
	swallow: {
		uk: "ковтати",
		en: "swallow",
		de: "schlucken",
		nl: "slikken",
		crh: "yutmaq",
		transcription: "ˈswɒləʊ",
	},
	tear_rip: {
		uk: "рвати",
		en: "tear",
		de: "zerreißen",
		nl: "scheuren",
		crh: "yırtmaq",
		transcription: "teə",
	},
	translate: {
		uk: "перекладати",
		en: "translate",
		de: "übersetzen",
		nl: "vertalen",
		crh: "tercime etmek",
		transcription: "trænzˈleɪt",
	},
	trust_verb: {
		uk: "довіряти",
		en: "trust",
		de: "vertrauen",
		nl: "vertrouwen",
		crh: "inanmaq",
		transcription: "trʌst",
	},
	vote: {
		uk: "голосувати",
		en: "vote",
		de: "wählen",
		nl: "stemmen",
		crh: "rey bermek",
		transcription: "vəʊt",
	},
	waste_misuse: {
		uk: "марнувати",
		en: "waste",
		de: "verschwenden",
		nl: "verspillen",
		crh: "israf etmek",
		transcription: "weɪst",
	},
	wave_verb: {
		uk: "махати",
		en: "wave",
		de: "winken",
		nl: "zwaaien",
		crh: "sallamaq",
		transcription: "weɪv",
	},
	badly: {
		uk: "погано",
		en: "badly",
		de: "schlecht",
		nl: "slecht",
		crh: "yaman",
		transcription: "ˈbædli",
	},
	quickly: {
		uk: "швидко",
		en: "quickly",
		de: "schnell",
		nl: "snel",
		crh: "tez",
		transcription: "ˈkwɪkli",
	},
	simply: {
		uk: "просто",
		en: "simply",
		de: "einfach",
		nl: "gewoon",
		crh: "adice",
		transcription: "ˈsɪmpli",
	},
	nowhere: {
		uk: "ніде",
		en: "nowhere",
		de: "nirgendwo",
		nl: "nergens",
		crh: "bir yerde",
		transcription: "ˈnəʊweə",
	},
	someone: {
		uk: "хтось",
		en: "someone",
		de: "jemand",
		nl: "iemand",
		crh: "kimse",
		transcription: "ˈsʌmwʌn",
	},
	something: {
		uk: "щось",
		en: "something",
		de: "etwas",
		nl: "iets",
		crh: "bir şey",
		transcription: "ˈsʌmθɪŋ",
	},
	somewhere: {
		uk: "десь",
		en: "somewhere",
		de: "irgendwo",
		nl: "ergens",
		crh: "bir yerde",
		transcription: "ˈsʌmweə",
	},
	although: {
		uk: "хоча",
		en: "although",
		de: "obwohl",
		nl: "hoewel",
		crh: "amma",
		transcription: "ɔːlˈðəʊ",
	},
	because_conjunction: {
		uk: "тому що",
		en: "because",
		de: "weil",
		nl: "omdat",
		crh: "çünki",
		transcription: "bɪˈkɒz",
	},
	but_conjunction: {
		uk: "але",
		en: "but",
		de: "aber",
		nl: "maar",
		crh: "amma",
		transcription: "bʌt",
	},
	or_conjunction: {
		uk: "або",
		en: "or",
		de: "oder",
		nl: "of",
		crh: "yaki",
		transcription: "ɔː",
	},
	so_2: {
		uk: "отже",
		en: "so",
		de: "also",
		nl: "dus",
		crh: "bunıñ içün",
		transcription: "səʊ",
	},
	that_pronoun: {
		uk: "той",
		en: "that",
		de: "dass",
		nl: "dat",
		crh: "şu",
		transcription: "ðæt",
	},
	annoyed: {
		uk: "роздратований",
		en: "annoyed",
		de: "verärgert",
		nl: "geërgerd",
		crh: "acuvli",
		transcription: "əˈnɔɪd",
	},
	anxious: {
		uk: "тривожний",
		en: "anxious",
		de: "besorgt",
		nl: "angstig",
		crh: "qasevetli",
		transcription: "ˈæŋkʃəs",
	},
	bored: {
		uk: "нудьгуючий",
		en: "bored",
		de: "gelangweilt",
		nl: "verveeld",
		crh: "sıqılğan",
		transcription: "bɔːd",
	},
	brilliant: {
		uk: "блискучий",
		en: "brilliant",
		de: "brillant",
		nl: "briljant",
		crh: "parlaq",
		transcription: "ˈbrɪljənt",
	},
	confused: {
		uk: "розгублений",
		en: "confused",
		de: "verwirrt",
		nl: "verward",
		crh: "şaşqın",
		transcription: "kənˈfjuːzd",
	},
	cruel: {
		uk: "жорстокий",
		en: "cruel",
		de: "grausam",
		nl: "wreed",
		crh: "zalım",
		transcription: "kruːəl",
	},
	depressed: {
		uk: "депресивний",
		en: "depressed",
		de: "deprimiert",
		nl: "depressief",
		crh: "mazun",
		transcription: "dɪˈprɛst",
	},
	disappointed: {
		uk: "розчарований",
		en: "disappointed",
		de: "enttäuscht",
		nl: "teleurgesteld",
		crh: "raatsız",
		transcription: "ˌdɪsəˈpɔɪntɪd",
	},
	embarrassed: {
		uk: "збентежений",
		en: "embarrassed",
		de: "verlegen",
		nl: "beschaamd",
		crh: "utanğan",
		transcription: "ɪmˈbærəst",
	},
	excited: {
		uk: "збуджений",
		en: "excited",
		de: "aufgeregt",
		nl: "opgewonden",
		crh: "eyecanlı",
		transcription: "ɪkˈsaɪtɪd",
	},
	frightened: {
		uk: "наляканий",
		en: "frightened",
		de: "verängstigt",
		nl: "bang",
		crh: "qorqqan",
		transcription: "ˈfraɪtnd",
	},
	generous: {
		uk: "щедрий",
		en: "generous",
		de: "großzügig",
		nl: "vrijgevig",
		crh: "comart",
		transcription: "ˈdʒɛnərəs",
	},
	honest: {
		uk: "чесний",
		en: "honest",
		de: "ehrlich",
		nl: "eerlijk",
		crh: "namuslı",
		transcription: "ˈɒnɪst",
	},
	jealous: {
		uk: "ревнивий",
		en: "jealous",
		de: "eifersüchtig",
		nl: "jaloers",
		crh: "qısqan",
		transcription: "ˈdʒɛləs",
	},
	keen: {
		uk: "завзятий",
		en: "keen",
		de: "leidenschaftlich",
		nl: "enthousiast",
		crh: "avesli",
		transcription: "kiːn",
	},
	miserable: {
		uk: "нещасний",
		en: "miserable",
		de: "elend",
		nl: "ellendig",
		crh: "bahtsız",
		transcription: "ˈmɪzərəb(ə)l",
	},
	negative_result: {
		uk: "негативний",
		en: "negative",
		de: "negativ",
		nl: "negatief",
		crh: "menfiy",
		transcription: "ˈnɛɡətɪv",
	},
	patient_2: {
		uk: "терплячий",
		en: "patient",
		de: "geduldig",
		nl: "geduldig",
		crh: "sabırlı",
		transcription: "ˈpeɪʃ(ə)nt",
	},
	positive: {
		uk: "позитивний",
		en: "positive",
		de: "positiv",
		nl: "positief",
		crh: "musbet",
		transcription: "ˈpɒzətɪv",
	},
	relaxed: {
		uk: "розслаблений",
		en: "relaxed",
		de: "entspannt",
		nl: "ontspannen",
		crh: "raat",
		transcription: "rɪˈlækst",
	},
	reliable: {
		uk: "надійний",
		en: "reliable",
		de: "zuverlässig",
		nl: "betrouwbaar",
		crh: "imayetli",
		transcription: "rɪˈlaɪəb(ə)l",
	},
	sensible: {
		uk: "розумний",
		en: "sensible",
		de: "vernünftig",
		nl: "verstandig",
		crh: "aqıllı",
		transcription: "ˈsɛnsɪb(ə)l",
	},
	sensitive: {
		uk: "чутливий",
		en: "sensitive",
		de: "sensibel",
		nl: "gevoelig",
		crh: "sezişli",
		transcription: "ˈsɛnsɪtɪv",
	},
	shocked: {
		uk: "шокований",
		en: "shocked",
		de: "schockiert",
		nl: "geschokt",
		crh: "şaşqın",
		transcription: "ʃɒkt",
	},
	stressed: {
		uk: "напружений",
		en: "stressed",
		de: "gestresst",
		nl: "gestrest",
		crh: "kergin",
		transcription: "strɛst",
	},
	strict: {
		uk: "суворий",
		en: "strict",
		de: "streng",
		nl: "streng",
		crh: "sert",
		transcription: "strɪkt",
	},
	surprised: {
		uk: "здивований",
		en: "surprised",
		de: "überrascht",
		nl: "verrast",
		crh: "şaşqın",
		transcription: "səˈpraɪzd",
	},
	talented: {
		uk: "талановитий",
		en: "talented",
		de: "begabt",
		nl: "getalenteerd",
		crh: "istidatlı",
		transcription: "ˈtæləntɪd",
	},
	against: {
		uk: "проти",
		en: "against",
		de: "gegen",
		nl: "tegen",
		crh: "qarşı",
		transcription: "əˈɡɛnst",
	},
	among: {
		uk: "серед",
		en: "among",
		de: "unter",
		nl: "onder",
		crh: "arasında",
		transcription: "əˈmʌŋ",
	},
	at: {
		uk: "в",
		en: "at",
		de: "bei",
		nl: "bij",
		crh: "yanında",
		transcription: "æt",
	},
	beside: {
		uk: "поруч",
		en: "beside",
		de: "neben",
		nl: "naast",
		crh: "yanında",
		transcription: "bɪˈsaɪd",
	},
	for: {
		uk: "для",
		en: "for",
		de: "für",
		nl: "voor",
		crh: "içün",
		transcription: "fɔː",
	},
	from: {
		uk: "з",
		en: "from",
		de: "von",
		nl: "van",
		crh: "-dan/-den",
		transcription: "frɒm",
	},
	in: {
		uk: "в",
		en: "in",
		de: "in",
		nl: "in",
		crh: "içinde",
		transcription: "ɪn",
	},
	to: {
		uk: "до",
		en: "to",
		de: "zu",
		nl: "naar",
		crh: "-qa/-ge",
		transcription: "tuː",
	},
	cash: {
		uk: "готівка",
		en: "cash",
		de: "Bargeld",
		nl: "contant geld",
		crh: "nağd para",
		transcription: "kæʃ",
	},
	credit_card: {
		uk: "кредитна картка",
		en: "credit card",
		de: "Kreditkarte",
		nl: "creditcard",
		crh: "kredi kartı",
		transcription: "ˈkrɛdɪt kɑːd",
	},
	crowd: {
		uk: "натовп",
		en: "crowd",
		de: "Menge",
		nl: "menigte",
		crh: "qalıbalıq",
		transcription: "kraʊd",
	},
	document: {
		uk: "документ",
		en: "document",
		de: "Dokument",
		nl: "document",
		crh: "vesiqa",
		transcription: "ˈdɒkjʊmənt",
	},
	license: {
		uk: "ліцензія (права)",
		en: "license",
		de: "Lizenz",
		nl: "licentie",
		crh: "ruhset",
		transcription: "ˈlaɪsəns",
	},
	luggage: {
		uk: "багаж",
		en: "luggage",
		de: "Gepäck",
		nl: "bagage",
		crh: "yük",
		transcription: "ˈlʌɡɪdʒ",
	},
	platform: {
		uk: "платформа",
		en: "platform",
		de: "Plattform",
		nl: "platform",
		crh: "platforma",
		transcription: "ˈplætfɔːm",
	},
	suitcase: {
		uk: "валіза",
		en: "suitcase",
		de: "Koffer",
		nl: "koffer",
		crh: "camadan",
		transcription: "ˈsuːtkeɪs",
	},
	tour: {
		uk: "тур",
		en: "tour",
		de: "Tour",
		nl: "tour",
		crh: "seyat",
		transcription: "tʊə",
	},
	parent_1: {
		uk: "батьки",
		en: "parent",
		de: "Elternteil",
		nl: "ouder",
		crh: "ana-baba",
		transcription: "ˈpeərənt",
	},
	fear: {
		uk: "страх",
		en: "fear",
		de: "Angst",
		nl: "angst",
		crh: "qorqu",
		transcription: "fɪə",
	},
	act: {
		uk: "діяти",
		en: "act",
		de: "handeln",
		nl: "handelen",
		crh: "areket etmek",
		transcription: "ækt",
	},
	brush: {
		uk: "щітка",
		en: "brush",
		de: "Bürste",
		nl: "borstel",
		crh: "fırça",
		transcription: "brʌʃ",
	},
	care: {
		uk: "турбота",
		en: "care",
		de: "Pflege",
		nl: "zorg",
		crh: "qayğı",
		transcription: "keə",
	},
	crash_1: {
		uk: "аварія",
		en: "crash",
		de: "Unfall",
		nl: "ongeluk",
		crh: "qaza",
		transcription: "kræʃ",
	},
	drive_1: {
		uk: "поїздка",
		en: "drive",
		de: "Fahrt",
		nl: "rit",
		crh: "yürüş",
		transcription: "draɪv",
	},
	exchange: {
		uk: "обмін",
		en: "exchange",
		de: "Austausch",
		nl: "uitwisseling",
		crh: "almaşuv",
		transcription: "ɪksˈtʃeɪndʒ",
	},
	matter_1: {
		uk: "матерія",
		en: "matter",
		de: "Materie",
		nl: "materie",
		crh: "madde",
		transcription: "ˈmætə",
	},
	perform: {
		uk: "виконувати",
		en: "perform",
		de: "aufführen",
		nl: "uitvoeren",
		crh: "icra etmek",
		transcription: "pəˈfɔːm",
	},
	point_1: {
		uk: "пункт",
		en: "point",
		de: "Punkt",
		nl: "punt",
		crh: "noqta",
		transcription: "pɔɪnt",
	},
	race_1: {
		uk: "гонка",
		en: "race",
		de: "Rennen",
		nl: "race",
		crh: "yarış",
		transcription: "reɪs",
	},
	reserve: {
		uk: "заповідник",
		en: "reserve",
		de: "Reservat",
		nl: "reservaat",
		crh: "qoruq",
		transcription: "rɪˈzɜːv",
	},
	score: {
		uk: "рахунок",
		en: "score",
		de: "Spielstand",
		nl: "score",
		crh: "esap",
		transcription: "skɔː",
	},
	anyway: {
		uk: "в будь-якому випадку",
		en: "anyway",
		de: "jedenfalls",
		nl: "hoe dan ook",
		crh: "er alda",
		transcription: "ˈɛniweɪ",
	},
	certainly: {
		uk: "звичайно",
		en: "certainly",
		de: "sicherlich",
		nl: "zeker",
		crh: "elbette",
		transcription: "ˈsɜːtnli",
	},
	themselves: {
		uk: "самі",
		en: "themselves",
		de: "selbst",
		nl: "zichzelf",
		crh: "özleri",
		transcription: "ðəmˈsɛlvz",
	},
	cheerful: {
		uk: "веселий",
		en: "cheerful",
		de: "fröhlich",
		nl: "vrolijk",
		crh: "şen",
		transcription: "ˈtʃɪəfʊl",
	},
	delighted: {
		uk: "задоволений",
		en: "delighted",
		de: "erfreut",
		nl: "verheugd",
		crh: "memnün",
		transcription: "dɪˈlaɪtɪd",
	},
	upset_verb: {
		uk: "засмучувати",
		en: "upset",
		de: "verärgern",
		nl: "van streek maken",
		crh: "keyfini bozmaq",
		transcription: "ʌpˈsɛt",
	},
	delay: {
		uk: "затримка",
		en: "delay",
		de: "Verzögerung",
		nl: "vertraging",
		crh: "keçiküv",
		transcription: "dɪˈleɪ",
	},
	insurance: {
		uk: "страхування",
		en: "insurance",
		de: "Versicherung",
		nl: "verzekering",
		crh: "sigorta",
		transcription: "ɪnˈʃʊərəns",
	},
	reception: {
		uk: "ресепшн",
		en: "reception",
		de: "Rezeption",
		nl: "receptie",
		crh: "qabul",
		transcription: "rɪˈsɛpʃ(ə)n",
	},
};
